# Generated by Django 5.1 on 2024-08-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO store_collection(title)
            VALUES('collection1')
            """,
            """
            DELETE FROM store_collection
            WHERE title='collection1'
            """
        ),
    ]